# https://github.com/brandtbucher/travis-python-matrix

# CPython 3.7.3 / CPython 3.6.8 / CPython 3.5.2
# Ubuntu 16.04 (Xenial Xerus) / Windows 10 / macOS 10.14 (Mojave)

git:

    depth: False

matrix:

  include:
  
    - name: CPython 3.7.3 on Ubuntu 16.04 (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.7.3

    - name: CPython 3.6.8 on Ubuntu 16.04 (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.6.8
      
    - name: CPython 3.5.2 on Ubuntu 16.04 (Xenial Xerus)
      language: python
      os: linux
      dist: xenial
      python: 3.5.2

    - name: CPython 3.7.3 on Windows 10
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - choco install python --version 3.7.3

    - name: CPython 3.6.8 on Windows 10
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - choco install python --version 3.6.8

    - name: CPython 3.5.2 on Windows 10
      language: shell
      os: windows
      before_install:
        - export PATH=/c/Python35:/c/Python35/Scripts:$PATH
        - choco install python --version 3.5.2.20161029

    - name: CPython 3.7.3 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode10.2
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.3
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION

    - name: CPython 3.6.8 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode10.2
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.8
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION

    - name: CPython 3.5.2 on macOS 10.14 (Mojave)
      language: shell
      os: osx
      osx_image: xcode10.2
      before_install:
        - export PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5.2
        - CFLAGS="-I$(xcrun --show-sdk-path)/usr/include" pyenv install $PYENV_VERSION

install: pip install --upgrade -r requirements.txt

script: invoke test

