language: shell

git:

    depth: False

matrix:

  include:
  
    - name: Python 3.5.2 on Linux
      python: 3.5.2
      dist: xenial
      language: python
      script: make build-35
      
    - name: Python 3.6.8 on Linux
      python: 3.6.8
      dist: xenial
      language: python

    - name: Python 3.7.3 on Linux
      python: 3.7.3
      dist: xenial
      language: python

    - name: Python 3.5.2 on Windows
      os: windows
      before_install: choco install make && choco install python --version 3.5.2.20161029
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
      script: make build-35

    - name: Python 3.6.8 on Windows
      os: windows
      before_install: choco install make && choco install python --version 3.6.8
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH

    - name: Python 3.7.3 on Windows
      os: windows
      before_install: choco install make && choco install python --version 3.7.3
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

    - name: Python 3.5.2 on macOS
      os: osx
      before_install: brew upgrade pyenv; pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.5.2
      script: make build-35

    - name: Python 3.6.8 on macOS
      os: osx
      before_install: brew upgrade pyenv; pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.6.8

    - name: Python 3.7.3 on macOS
      os: osx
      before_install: brew upgrade pyenv; pyenv install $PYENV_VERSION
      env: PATH=/Users/travis/.pyenv/shims:$PATH PYENV_VERSION=3.7.3

install: pip install --upgrade setuptools

script: make test

