dist: xenial
install: pip install --upgrade setuptools
language: python
python: 3.7
script: make test

git:

  depth: False

matrix:

  allow_failures:

  - python: 3.5-dev
  - python: 3.6-dev
  - python: 3.7-dev
  - python: 3.8-dev

  fast_finish: True

  include:

  - name: CPython 3.5
    python: 3.5
    script: make build-35

  - name: CPython 3.6
    python: 3.6

  - name: CPython 3.7
    python: 3.7

  - name: CPython 3.5+
    python: 3.5-dev
    script: make build-35

  - name: CPython 3.6+
    python: 3.6-dev

  - name: CPython 3.7+
    python: 3.7-dev

  - name: CPython 3.8+
    python: 3.8-dev
